### ISSUE TITLE
想使用GPUDirect RDMA，请问如何保证GPU卡和RDMA网卡在同一个ROOT COMPLEX下？

### ISSUE THREAD

**Issue by tangrenzhi** [FelixFu520/README#1]
在运行代码时发出这个提醒，请问在dell R740如何保证这个条件呢，网卡和显卡已经插在了同一个pcie扩展卡上。谢谢。

**Comment by FelixFu520** [comment]
能详细说下么？没看懂问题是什么

**Comment by tangrenzhi** [comment]
> 能详细说下么？没看懂问题是什么

在您的“GPU&CUDA多机通信”-》“GPUDirect RDMA” 9.4 中需要注意的是，要想使用GPUDirect RDMA，需要保证GPU卡和RDMA网卡在同一个ROOT COMPLEX下。我在开发GPUDirect RDMA的程序，遇到了这个问题（达不到最好的传输性能）请问您对这方面了解吗？

**Comment by FelixFu520** [comment]
这个需要在装硬件的时候，把网卡和GPU插到同一个PCIE上。
可以使用lspci命令来查看，网卡和GPU的拓扑结构
(base) user@ubuntu:~$ lspci -tv
-+-[0000:d7]-+-00.0-[d8]----00.0  Broadcom / LSI MegaRAID SAS-3 3108 [Invader]
 |           +-05.0  Intel Corporation Sky Lake-E VT-d
 |           +-05.2  Intel Corporation Sky Lake-E RAS Configuration Registers
 +-[0000:ae]-+-00.0-[af]----00.0  NVIDIA Corporation Device 20f1
 |           +-05.0  Intel Corporation Sky Lake-E VT-d
 |           +-05.2  Intel Corporation Sky Lake-E RAS Configuration Registers
 |           +-05.4  Intel Corporation Sky Lake-E IOxAPIC Configuration Registers
 +-[0000:85]-+-00.0-[86]----00.0  NVIDIA Corporation Device 20f1
 |           +-05.0  Intel Corporation Sky Lake-E VT-d
 +-[0000:80]-+-04.0  Intel Corporation Sky Lake-E CBDMA Registers
 |           +-04.1  Intel Corporation Sky Lake-E CBDMA Registers
 |           +-04.2  Intel Corporation Sky Lake-E CBDMA Registers
 |           +-04.3  Intel Corporation Sky Lake-E CBDMA Registers
 +-[0000:5d]-+-05.0  Intel Corporation Sky Lake-E VT-d
 |           +-05.2  Intel Corporation Sky Lake-E RAS Configuration Registers
 |           +-05.4  Intel Corporation Sky Lake-E IOxAPIC Configuration Registers
 |           \-16.5  Intel Corporation Sky Lake-E DDRIO Registers
 +-[0000:3a]-+-00.0-[3b]----00.0  NVIDIA Corporation Device 20f1
 |           +-05.0  Intel Corporation Sky Lake-E VT-d
 |           +-05.2  Intel Corporation Sky Lake-E RAS Configuration Registers
 +-[0000:17]-+-00.0-[18]----00.0  NVIDIA Corporation Device 20f1
 |           +-05.0  Intel Corporation Sky Lake-E VT-d
 
 \-[0000:00]-+-00.0  Intel Corporation Sky Lake-E DMI3 Registers
             +-04.0  Intel Corporation Sky Lake-E CBDMA Registers
             +-1c.0-[01]--+-00.0  Intel Corporation Ethernet Controller 10G X550T
             |            \-00.1  Intel Corporation Ethernet Controller 10G X550T
             +-1d.0-[02]--


然后，看下这个连接https://www.cnblogs.com/machangwei-8/p/10403495.html，看下设备的地址表示的含义，这样就可以知道主机中的网卡和GPU是否在同一个PCIE下了。
如果机器是购买的，最好问下厂商

**Comment by tangrenzhi** [comment]
> 这个需要在装硬件的时候，把网卡和GPU插到同一个PCIE上。 可以使用lspci命令来查看，网卡和GPU的拓扑结构 (base) user@ubuntu:~$ lspci -tv -+-[0000:d7]-+-00.0-[d8]----00.0 Broadcom / LSI MegaRAID SAS-3 3108 [Invader] | +-05.0 Intel Corporation Sky Lake-E VT-d | +-05.2 Intel Corporation Sky Lake-E RAS Configuration Registers +-[0000:ae]-+-00.0-[af]----00.0 NVIDIA Corporation Device 20f1 | +-05.0 Intel Corporation Sky Lake-E VT-d | +-05.2 Intel Corporation Sky Lake-E RAS Configuration Registers | +-05.4 Intel Corporation Sky Lake-E IOxAPIC Configuration Registers +-[0000:85]-+-00.0-[86]----00.0 NVIDIA Corporation Device 20f1 | +-05.0 Intel Corporation Sky Lake-E VT-d +-[0000:80]-+-04.0 Intel Corporation Sky Lake-E CBDMA Registers | +-04.1 Intel Corporation Sky Lake-E CBDMA Registers | +-04.2 Intel Corporation Sky Lake-E CBDMA Registers | +-04.3 Intel Corporation Sky Lake-E CBDMA Registers +-[0000:5d]-+-05.0 Intel Corporation Sky Lake-E VT-d | +-05.2 Intel Corporation Sky Lake-E RAS Configuration Registers | +-05.4 Intel Corporation Sky Lake-E IOxAPIC Configuration Registers | -16.5 Intel Corporation Sky Lake-E DDRIO Registers +-[0000:3a]-+-00.0-[3b]----00.0 NVIDIA Corporation Device 20f1 | +-05.0 Intel Corporation Sky Lake-E VT-d | +-05.2 Intel Corporation Sky Lake-E RAS Configuration Registers +-[0000:17]-+-00.0-[18]----00.0 NVIDIA Corporation Device 20f1 | +-05.0 Intel Corporation Sky Lake-E VT-d
> 
> -[0000:00]-+-00.0 Intel Corporation Sky Lake-E DMI3 Registers +-04.0 Intel Corporation Sky Lake-E CBDMA Registers +-1c.0-[01]--+-00.0 Intel Corporation Ethernet Controller 10G X550T | -00.1 Intel Corporation Ethernet Controller 10G X550T +-1d.0-[02]--
> 
> 然后，看下这个连接[https://www.cnblogs.com/machangwei-8/p/10403495.html，看下设备的地址表示的含义，这样就可以知道主机中的网卡和GPU是否在同一个PCIE下了。](https://www.cnblogs.com/machangwei-8/p/10403495.html%EF%BC%8C%E7%9C%8B%E4%B8%8B%E8%AE%BE%E5%A4%87%E7%9A%84%E5%9C%B0%E5%9D%80%E8%A1%A8%E7%A4%BA%E7%9A%84%E5%90%AB%E4%B9%89%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9F%A5%E9%81%93%E4%B8%BB%E6%9C%BA%E4%B8%AD%E7%9A%84%E7%BD%91%E5%8D%A1%E5%92%8CGPU%E6%98%AF%E5%90%A6%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AAPCIE%E4%B8%8B%E4%BA%86%E3%80%82) 如果机器是购买的，最好问下厂商

非常谢谢。
